#!/bin/bash

if [ "$#" -ne 5 ]; then
    echo "Usage: $0 <AWS_ACCESS_KEY_ID> <AWS_SECRET_ACCESS_KEY> <DATABASE_HOST> <DATABASE_USER> <DATABASE_PASSWORD>"
    exit 1
fi

AWS_ACCESS_KEY_ID=$1
AWS_SECRET_ACCESS_KEY=$2
DATABASE_HOST=$3
DATABASE_USER=$4
DATABASE_PASSWORD=$5

docker build -t db-connector .

docker run -p 1337:1337 -d -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e DATABASE_HOST=${DATABASE_HOST} -e DATABASE_USER=${DATABASE_USER} -e DATABASE_PASSWORD=${DATABASE_PASSWORD} --name connector db-connector
